@url = http://localhost:8080/api/appuser

### GET findAll()

GET {{url}} HTTP/1.1

### GET findById()

GET {{url}}/1 HTTP/1.1

###
# ### PUT
# PUT {{url}}/register HTTP/1.1
# Content-Type: application/json

# {
#     "userId": ""
#     "firstName": "bobb",
#     "lastName":   "jones",
#     "username": "bob@jones.com",
#     "password": "P@ssw0rd!",
# }

DELETE {{url}}/6 HTTP/1.1

