@url = http://localhost:8080/api

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "bob",
    "lastName":   "jones",
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

GET http://localhost:8080/api/appuser/username/testUser HTTP/1.1


### POST (register user)
POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "robert",
    "lastName": "marley",
    "username": "bob@marley.com",
    "password": "P@ssw0rd!"
}

### POST (user login)
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@marley.com",
    "password": "P@ssw0rd!"
}